import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

import Sidebar from '@/components/Sidebar';
import AppContext from '@/context/AppContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AppContext>
          <Header />
          <div className='w-screen flex'>
            <Sidebar />

            {children}
          </div>
        </AppContext>
      </body>
    </html>
  );
}
